# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0003_auto_20170503_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='sports',
            field=models.ManyToManyField(to='tableaubord.Sport'),
        ),
    ]
