# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 08:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0004_evenement_sports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='heure',
        ),
        migrations.AddField(
            model_name='evenement',
            name='dateheure',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 7, 8, 43, 37, 362747), verbose_name='Date/heure evenement '),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='dateNaissance',
            field=models.DateField(default=datetime.date.today, verbose_name='Date de naissance'),
        ),
    ]
