# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 11:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0008_auto_20170507_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='photoProfil',
        ),
        migrations.AlterField(
            model_name='evenement',
            name='dateheure',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 7, 11, 2, 58, 714259), verbose_name='Date/heure evenement '),
        ),
    ]
