# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 18:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0017_auto_20170507_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(default='cat.jpg', upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='dateheure',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 7, 18, 45, 27, 550884), verbose_name='Date/heure evenement '),
        ),
    ]
