# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 00:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0043_auto_20170507_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='dateheure',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 8, 0, 45, 36, 997480), verbose_name='Date/heure evenement '),
        ),
    ]
