# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 11:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0046_auto_20170508_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='dateheure',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 8, 11, 22, 22, 239948), verbose_name='Date/heure evenement '),
        ),
    ]
