# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 12:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0048_auto_20170508_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='dateheure',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 8, 12, 34, 52, 893556), verbose_name='Date/heure evenement '),
        ),
    ]
