# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 18:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0051_auto_20170508_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='dateheure',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 8, 18, 21, 21, 857638), verbose_name='Date/heure evenement '),
        ),
    ]
