# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0054_auto_20170509_1851'),
        ('tableaubord', '0046_auto_20170508_1341'),
    ]

    operations = [
    ]
