# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 21:22
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0055_merge_20170509_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='dateheure',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 9, 21, 22, 2, 904734), verbose_name='Date/heure evenement '),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
