# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 22:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0058_auto_20170509_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='dateheure',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 9, 22, 41, 26, 122171), verbose_name='Date/heure evenement '),
        ),
    ]
