# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0056_auto_20170509_2122'),
        ('tableaubord', '0061_auto_20170509_2255'),
    ]

    operations = [
    ]
