# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0062_auto_20170510_0658'),
        ('tableaubord', '0062_merge_20170510_0617'),
    ]

    operations = [
    ]
