# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 22:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0070_auto_20170510_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='dateheure',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 22, 6, 39, 200283), verbose_name='Date/heure evenement '),
        ),
    ]
