# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0071_auto_20170510_2206'),
        ('tableaubord', '0064_merge_20170510_1439'),
    ]

    operations = [
    ]
