# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 23:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0072_merge_20170510_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='dateheure',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 10, 23, 0, 51, 456646), verbose_name='Date/heure evenement '),
        ),
    ]
