# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 01:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0073_auto_20170510_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='dateheure',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 11, 1, 12, 40, 720803), verbose_name='Date/heure evenement '),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='dateNaissance',
            field=models.DateField(blank=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='tel',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
