# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 10:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0074_auto_20170511_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='photo',
            field=models.ImageField(default='photoSports/cap.jpeg', upload_to='photoSports/'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='dateheure',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 11, 10, 10, 42, 770221), verbose_name='Date/heure evenement '),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='dateNaissance',
            field=models.DateField(default=datetime.date.today, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='tel',
            field=models.CharField(max_length=12),
        ),
    ]
