# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 15:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0075_auto_20170511_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='dateheure',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 11, 15, 59, 45, 159600), verbose_name='Date/heure evenement '),
        ),
    ]
