# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 16:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0076_auto_20170511_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='dateheure',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 11, 16, 27, 44, 134629), verbose_name='Date/heure evenement '),
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='sports',
        ),
        migrations.AddField(
            model_name='evenement',
            name='sports',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tableaubord.Sport'),
        ),
    ]
