# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 17:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0077_auto_20170511_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='dateheure',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 11, 17, 31, 58, 872509), verbose_name='Date/heure evenement '),
        ),
    ]
