# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 18:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0078_auto_20170511_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='dateheure',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 11, 18, 18, 48, 405446), verbose_name='Date/heure evenement '),
        ),
    ]
