# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 16:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0080_auto_20170511_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='dateheure',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 12, 16, 31, 52, 185211), verbose_name='Date/heure evenement '),
        ),
    ]
