# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 19:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0081_auto_20170512_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='dateheure',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 12, 19, 42, 43, 752793), verbose_name='Date/heure evenement '),
        ),
    ]
