# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 19:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0082_auto_20170512_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='photoEvt',
            field=models.ImageField(default='photoEvt/evtbase.png', upload_to='photoEvt/'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='dateheure',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 12, 19, 49, 17, 267236), verbose_name='Date/heure evenement '),
        ),
    ]
