# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 19:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0083_auto_20170512_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='dateheure',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 12, 19, 56, 26, 510734), verbose_name='Date/heure evenement '),
        ),
    ]
