# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 09:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0086_auto_20170513_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 13, 9, 19, 49, 479207), verbose_name='Date événement'),
        ),
    ]
