# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 09:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0087_auto_20170513_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 13, 9, 41, 3, 388584), verbose_name='Date evenement'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='heure',
            field=models.CharField(default='Pas heure', max_length=20),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='nbPlaces',
            field=models.IntegerField(verbose_name='Nombre de places'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='photoEvt',
            field=models.ImageField(default='photoEvt/evtbase.png', upload_to='photoEvt/'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='sexe',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6),
        ),
    ]
