# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 09:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0089_auto_20170513_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 13, 9, 56, 14, 446700), verbose_name='Date événement'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='heure',
            field=models.CharField(default='Heure indéfinie', max_length=20),
        ),
    ]
