# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 09:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0090_auto_20170513_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='placesRestantes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 13, 9, 59, 37, 214601), verbose_name='Date evenement'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='heure',
            field=models.CharField(default='Pas heure', max_length=20),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='nbPlaces',
            field=models.IntegerField(),
        ),
    ]
