# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 14:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0093_auto_20170513_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 14, 14, 9, 14, 717333), verbose_name='Date événement'),
        ),
    ]
