# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 08:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0094_auto_20170514_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 15, 8, 40, 14, 832782), verbose_name='Date événement'),
        ),
    ]
