# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 11:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0095_auto_20170515_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 17, 11, 5, 49, 163483), verbose_name='Date événement'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='sexe',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Oui SVP')], max_length=6),
        ),
    ]
