# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 13:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0096_auto_20170517_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 17, 13, 35, 4, 866017), verbose_name='Date événement'),
        ),
    ]
