# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 20:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableaubord', '0098_auto_20170523_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 23, 20, 14, 57, 617344), verbose_name='Date événement'),
        ),
    ]
